### PR TITLE
Add support for Chronos-Bolt in notebook and benchmark results

### PR DESCRIPTION
**Pull request by abdulfatir**
This PR adds support for Chronos-Bolt models in the chronos notebook. Now both Chronos and Chronos-Bolt are supported. Other changes:

- Used PyPi install instead of source install for `chronos-forecasting`.
- Ran code formatting and import sorting.
- Removed unused imports. 
- Added a warning filter to mute warnings from the `QuantileForecast` object about the mean. 

Also adds the CSV and `config.json` for the following models. Metrics were generated using the updated chronos notebook.

- [x] `chronos_bolt_base`
- [x] `chronos_bolt_small`

### CODE REVIEW

**Comment by liu-jc** [comment]
Hi @abdulfatir,

Thanks for your contribution! Could you please also provide the model link like [here](https://huggingface.co/spaces/Salesforce/GIFT-Eval/blob/5f6be9e3ba65353e23135d58bb1e568832750d79/results/Chronos_small/config.json#L5)? It will create the hyperlink for your models on the leaderboard.

**Comment by liam-sbhoo** [comment]
@abdulfatir 

I have a quick question regarding the evaluation of Chronos-Bolt here: are the models pretrained on the GIFT-EVAL pretraining split, or are the models using the pretraining from the Chronos paper?

Thank you :)

**Comment by abdulfatir** [comment]
@liam-sbhoo No, Chronos-Bolt models have NOT been trained on GIFT-Eval. The real datasets used for pretraining Chronos-Bolt are same as in the Chronos paper. However, there are two changes in the pretraining set:
- We generated more TSMixup augementations than before (using the same real datasets as in Chronos).
- We improved our synthetic time series generation procedure to include patterns missed by the previous approach (e.g., step function, spiky data, triangular patterns, etc.)

Note that Chronos-Bolt models had been pretrained well before GIFT-Eval was open sourced. The great performance of Chronos-Bolt on GIFT-Eval was a happy holiday gift (pun intended) for us! ;)

**Comment by liam-sbhoo** [comment]
@abdulfatir 

Thanks for the explanation! I have a follow up: do you think there might be chances that the evaluation (test) split in GIFT-EVAL overlaps with the real datasets used for pretraining Chronos-Bolt and Chronos?

Btw, I guess we all loved this holiday gift from your team :)

**Comment by abdulfatir** [comment]
@liam-sbhoo I haven't carefully analyzed the splits for individual datasets, so I am not completely sure. I quickly skimmed through the dataset list and I think electricity and solar maybe the two datasets with some overlap, but again, I did not check carefully, so please take this with a grain of salt.

**Pull request merged**
